### ISSUE TITLE
Issue when deserializing with jms/serializer

### ISSUE THREAD

**Issue by RSully** [goetas/xsd2php#22]
I'm getting this error when trying to use this with the deserializer:

> PHP Fatal error:  Uncaught exception 'JMS\Serializer\Exception\RuntimeException' with message 'You must define a type for Test\OrderRequestType::$orderRequestHeader.' in /dev/xcbl/wsd2php-mine/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:213

---

Executed:

```
php -d memory_limit=-1 vendor/goetas/xsd2php/bin/xsd2php.php convert:php --ns-map='rrn:org.xcbl:schemas/xcbl/v3_0/xcbl30.xsd;Test/' --ns-dest='Test/;src/Test' ../xsdcblcomponents30r2/XCBL30.xsd
php -d memory_limit=-1 vendor/goetas/xsd2php/bin/xsd2php.php convert:jms-yaml --ns-map='rrn:org.xcbl:schemas/xcbl/v3_0/xcbl30.xsd;Test/' --ns-dest='Test/;src/Test' ../xsdcblcomponents30r2/XCBL30.xsd
```

JMS code used:

``` php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$serializer = JMS\Serializer\SerializerBuilder::create()
    ->addMetadataDir('src/Test/')
    ->build();

$exampleData = file_get_contents('orderreq.xml');
$exampleClass = 'Test\OrderRequest';

$object = $serializer->deserialize($exampleData, $exampleClass, 'xml');

var_dump($object);
```

Generated code:

``` php
<?php namespace Test;

class OrderRequest extends OrderRequestType {}
```

``` php
<?php namespace Test;

/**
 * XSD Type: OrderRequest
 */
class OrderRequestType
{

    /**
     * @var \Test\OrderRequestHeaderType
     */
    protected $orderRequestHeader;


    // snip    


    /**
     * @return \Test\OrderRequestHeaderType
     */
    public function getOrderRequestHeader()
    {
        return $this->orderRequestHeader;
    }
    /**
     * @param $orderRequestHeader \Test\OrderRequestHeaderType
     * @return \Test\OrderRequestType
     */
    public function setOrderRequestHeader(\Test\OrderRequestHeaderType $orderRequestHeader)
    {
        $this->orderRequestHeader = $orderRequestHeader;
        return $this;
    }

    // snip

}
```

``` yaml
Test\OrderRequest:
    properties:
        orderRequestHeader:
            expose: true
            access_type: public_method
            serialized_name: OrderRequestHeader
            xml_element:
                namespace: 'rrn:org.xcbl:schemas/xcbl/v3_0/xcbl30.xsd'
            accessor:
                getter: getOrderRequestHeader
                setter: setOrderRequestHeader
            type: Test\OrderRequestHeader
        orderRequestDetail:
            expose: true
            access_type: public_method
            serialized_name: OrderRequestDetail
            xml_element:
                namespace: 'rrn:org.xcbl:schemas/xcbl/v3_0/xcbl30.xsd'
            accessor:
                getter: getOrderRequestDetail
                setter: setOrderRequestDetail
            type: Test\OrderRequest\OrderRequestDetailType
        orderRequestSummary:
            expose: true
            access_type: public_method
            serialized_name: OrderRequestSummary
            xml_element:
                namespace: 'rrn:org.xcbl:schemas/xcbl/v3_0/xcbl30.xsd'
            accessor:
                getter: getOrderRequestSummary
                setter: setOrderRequestSummary
            type: Test\OrderRequest\OrderRequestSummaryType
```
