### ISSUE TITLE
JMS YAML for xs:dateTime does not cast to DateTime<'c'>

### ISSUE THREAD

**Issue by rtek** [goetas/xsd2php#39]
Attempting to deserialize an object with an xs:dateTime element is resulting in an error:

```
ReflectionException: Class Goetas\Xsd\XsdToPhp\XMLSchema\DateTime does not exist
vendor\jms\metadata\src\Metadata\MetadataFactory.php:167
vendor\jms\metadata\src\Metadata\MetadataFactory.php:72
vendor\jms\serializer\src\JMS\Serializer\GraphNavigator.php:180
vendor\jms\serializer\src\JMS\Serializer\XmlDeserializationVisitor.php:278
vendor\jms\serializer\src\JMS\Serializer\GraphNavigator.php:227
vendor\jms\serializer\src\JMS\Serializer\XmlDeserializationVisitor.php:278
vendor\jms\serializer\src\JMS\Serializer\GraphNavigator.php:227
vendor\jms\serializer\src\JMS\Serializer\XmlDeserializationVisitor.php:167
vendor\jms\serializer\src\JMS\Serializer\GraphNavigator.php:129
vendor\jms\serializer\src\JMS\Serializer\XmlDeserializationVisitor.php:252
vendor\jms\serializer\src\JMS\Serializer\GraphNavigator.php:227
vendor\jms\serializer\src\JMS\Serializer\Serializer.php:114
```

The JMS type should be DateTime<'c'>:

``` xml

    <xs:element name="log" type="logType"/>
    <xs:complexType name="logType">
        <xs:sequence>       
            <xs:element name="createdDate" type="xs:dateTime" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>The date and time stamp the record was created (in EST).  This information is only available in an XML response.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
```

``` php
class LogType
{

    /**
     * @property \DateTime $createdDate
     */
    private $createdDate = null;

     /**
     * @return \DateTime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }

    /**
     * @param \DateTime $createdDate
     * @return self
     */
    public function setCreatedDate(\DateTime $createdDate)
    {
        $this->createdDate = $createdDate;
        return $this;
    }
}
```

``` yaml
LogType:
    properties:      
        createdDate:
            expose: true
            access_type: public_method
            serialized_name: createdDate
            accessor:
                getter: getCreatedDate
                setter: setCreatedDate
            type: Goetas\Xsd\XsdToPhp\XMLSchema\DateTime
```
