### ISSUE TITLE
deserialization creates an empty object

### ISSUE THREAD

**Issue by PierreY** [goetas/xsd2php#46]
I'm using deserialization from a Symfony 2 application.
I'm using a very simple XML document:

``` XML
        $xml = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<ct>
    <transfer>
        <vrm>ZAZ</vrm>
        <date_on>2007-05-17</date_on>
        <date_off>2007-05-17</date_off>
    </transfer>
</ct>
XML;
```

Here is my ModelFromXSD.Transfer:

``` YML
MyBundle\ModelFromXSD\Transfer:
    properties:
        dateOn:
            expose: true
            access_type: public_method
            serialized_name: date_on
            xml_element:
                namespace: 'myTool'
            accessor:
                getter: getDateOn
                setter: setDateOn
            type: 'DateTime<''Y-m-d''>'
        dateOff:
            expose: true
            access_type: public_method
            serialized_name: date_off
            xml_element:
                namespace: 'myTool'
            accessor:
                getter: getDateOff
                setter: setDateOff
            type: 'DateTime<''Y-m-d''>'
        vrm:
            expose: true
            access_type: public_method
            serialized_name: vrm
            xml_element:
                namespace: 'myTool'
            accessor:
                getter: getVrm
                setter: setVrm
            type: string
```

Here is a part of my model object:

``` PHP
<?php

namespace  MyBundle\ModelFromXSD;

class Transfer
{

    /**
     * @property \DateTime $dateOn
     */
    private $dateOn = null;

    /**
     * @property \DateTime $dateOff
     */
    private $dateOff = null;

    /**
     * @property string $vrm
     */
    private $vrm = null;

    /**
     * Gets as dateOn
     *
     * @return \DateTime
     */
    public function getDateOn()
    {
        return $this->dateOn;
    }

[...]
```

Here is my call from a controller:

``` PHP
        $serializer = $this->container->get('jms_serializer');
        $object = $serializer->deserialize($xml, 'App\MyBundle\ModelFromXSD\Transfer', 'xml');
```

My problem is that the object is empty. A var_dump on it would give:
object(MyBundle\ModelFromXSD\Transfer)[304]
  private 'dateOn' => null
  private 'dateOff' => null
  private 'vrm' => null

I debugged it and went inside $serializer object, and then inside the GraphNavigator. The object is created here:

``` PHP
                if ($context instanceof DeserializationContext) {
                    $object = $this->objectConstructor->construct($visitor, $metadata, $data, $type, $context);
                }
```

At this point it seems I have everything needed:
- I checked $metadata and I found the good types
- I checked the object $data and it contains the rights values from XML
- $type contains the name of the class Transfer so I think that's ok
- I'm not sure about what $context and $visitor should/shouldn't be but I didn't see anything weird

Then the debug is going to the class UnserializeObjectConstructor and try to execute:

``` PHP
return unserialize(sprintf('O:%d:"%s":0:{}', strlen($metadata->name), $metadata->name));
```

After that it comes back to Serializer and my object is impossible to open in debug. 

First question: 
- Do I have a way to debug the unserialize function?
  Second question: 
- Why does UnserializeObjectConstructor accepts parameters like $visitor, $data, $context which aren't used when we call unserialize?
  Final question:
- Any chance someone would know why my returned object is empty?
