### ISSUE TITLE
Unnecessary namespace

### ISSUE THREAD

**Issue by hiend** [goetas/xsd2php#48]
Hi, is unnecessary namespace:

``` yml
Vendor\MyBundle\Model\ClassName:
    properties:
        some-property:
            xml_list:
                namespace:
```

http://jmsyst.com/libs/serializer/master/reference/yml_reference
