### ISSUE TITLE
handle extension tags

### ISSUE THREAD

**Issue by t128** [goetas/xsd2php#55]
hi,

i have an issue with a xsd file(http://www.datex2.eu/schema/2/2_0/DATEXIISchema_2_2_0.xsd). It is using a few `<extension>` tags eg. on line 3169. But it looks to me like they are not properly handled by xsd2php.

**Comment by t128** [comment]
yes, it creates also this:
```
NN\NnVis\Datex2\PayloadPublicationType:
    properties:
        lang:
            expose: true
            access_type: public_method
            serialized_name: lang
            accessor:
                getter: getLang
                setter: setLang
            xml_attribute: true
            type: string
        feedDescription:
            expose: true
            access_type: public_method
            serialized_name: feedDescription
            xml_element:
                namespace: 'http://datex2.eu/schema/2/2_0'
            accessor:
                getter: getFeedDescription
                setter: setFeedDescription
            type: NN\NnVis\Datex2\MultilingualStringType
        feedType:
            expose: true
            access_type: public_method
            serialized_name: feedType
            xml_element:
                namespace: 'http://datex2.eu/schema/2/2_0'
            accessor:
                getter: getFeedType
                setter: setFeedType
            type: string
        publicationTime:
            expose: true
            access_type: public_method
            serialized_name: publicationTime
            xml_element:
                namespace: 'http://datex2.eu/schema/2/2_0'
            accessor:
                getter: getPublicationTime
                setter: setPublicationTime
            type: Goetas\Xsd\XsdToPhp\XMLSchema\DateTime
        publicationCreator:
            expose: true
            access_type: public_method
            serialized_name: publicationCreator
            xml_element:
                namespace: 'http://datex2.eu/schema/2/2_0'
            accessor:
                getter: getPublicationCreator
                setter: setPublicationCreator
            type: NN\NnVis\Datex2\InternationalIdentifierType
        payloadPublicationExtension:
            expose: true
            access_type: public_method
            serialized_name: payloadPublicationExtension
            xml_element:
                namespace: 'http://datex2.eu/schema/2/2_0'
            accessor:
                getter: getPayloadPublicationExtension
                setter: setPayloadPublicationExtension
            type: NN\NnVis\Datex2\ExtensionType
```

there should now be an accesor for *situation* and *situationPublicationExtension*
