### ISSUE TITLE
question to unbounded

### ISSUE THREAD

**Issue by michabbb** [goetas/xsd2php#65]
hi there, 
i have a xsd like this (snippet):

````xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="plesk_client.xsd"/>
	<xs:complexType name="ResellerInput">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="add" type="ResellerAddInput"/>
			<xs:element name="set" type="ResellerSetInput"/>
			<xs:element name="get" type="ResellerGetInput"/>
			<xs:element name="del" type="ResellerDelInput"/>
			<xs:element name="ippool-add-ip" type="ResellerIpPoolOperation">
				<xs:annotation>
					<xs:documentation>Add IP address(es) to reseller's/client's IP pool</xs:documentation>
				</xs:annotation>
			</xs:element>
````

the generated classes look okay:

`````php
class ResellerInputType
{

    /**
     * @property \macropage\sdks\plesk\types\ResellerAddInputType[] $add
     */
    private $add = null;

/**
     * Sets a new add
     *
     * @param \macropage\sdks\plesk\types\ResellerAddInputType[] $add
     * @return self
     */
    public function setAdd($add)
    {
        $this->add[] = $add;
        return $this;
    }
````

code looks like this:

````php
            $ResellerInput = new ResellerAddInputType();
            $ResellerInput->setGenInfo($GenInfos);
            $Reseller = new ResellerInputType();
            $Reseller->setAdd($ResellerInput);
````

when i create my object and later convert back to xml the framework somehwere creates
me a tag called "entry", this is what i get:

````xml
<?xml version="1.0" encoding="UTF-8"?>
<packet>
  <reseller>
    <add>
      <entry>
        <gen-info>
          <cname>xxxxxxxxxxxxxx</cname>
          <pname>xxxxxxxxxxxx</pname>
          <login>xxxxxxxx</login>
          <passwd>xxxxxxxx</passwd>
          <phone>xxxxxxx</phone>
          <fax>xxxxxxx</fax>
          <email>xxxxxxx</email>
        </gen-info>
        <plan-name>xxxxxxx</plan-name>
      </entry>
    </add>
  </reseller>
</packet>
````

i don´t know where the *entry* tag is comming from ;-((

thanks for any help!

**Comment by goetas** [comment]
Can you post also the generated YAML?

**Comment by goetas** [comment]
Are you using the modified jms-serializer as explained on the `readme.md`?

**Comment by michabbb** [comment]
sorry if that is a stupid question, i am only working a few hours with this great framework: how do i get the "generated yaml" ? i did copy&paste from the readme to get my xml....

**Comment by goetas** [comment]
ahhhh.... to generate the yaml configuration you need to run [this](https://github.com/goetas/xsd2php#serialize--unserialize) and to setup the serializer explained some lines later...

BTW:

```php
use JMS\Serializer\SerializerBuilder;
use JMS\Serializer\Handler\HandlerRegistryInterface;

use Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler;
use Goetas\Xsd\XsdToPhp\Jms\Handler\XmlSchemaDateHandler;

$serializerBuilder = SerializerBuilder::create();
$serializerBuilder->addMetadataDir('metadata dir', 'DemoNs');
$serializerBuilder->configureHandlers(function (HandlerRegistryInterface $handler) use ($serializerBuilder) {
    $serializerBuilder->addDefaultHandlers();
    $handler->registerSubscribingHandler(new BaseTypesHandler()); 
    $handler->registerSubscribingHandler(new XmlSchemaDateHandler());
});

$serializer = $serializerBuilder->build();

// deserialize the XML into Demo\MyObject object
$object = $serializer->deserialize('<some xml/>', 'DemoNs\MyObject', 'xml');

// some code ....

// serialize the Demo\MyObject back into XML
$newXml = $serializer->serialize($object, 'xml');
```

**Comment by michabbb** [comment]
okay, thanks a lot for your support, i will try to deliver the yaml....

**Comment by michabbb** [comment]
dear asmir, i hope this is, what you wanted to see, thanks again for your help!!

````yaml
macropage\sdks\plesk\types\ResellerInputType:
    properties:
        add:
            expose: true
            access_type: public_method
            serialized_name: add
            accessor:
                getter: getAdd
                setter: setAdd
            xml_list:
                inline: true
                entry_name: add
            type: array<macropage\sdks\plesk\types\ResellerAddInputType>
        set:
            expose: true
            access_type: public_method
            serialized_name: set
            accessor:
                getter: getSet
                setter: setSet
            xml_list:
                inline: true
                entry_name: set
            type: array<macropage\sdks\plesk\types\ResellerSetInputType>
        get:
            expose: true
            access_type: public_method
            serialized_name: get
            accessor:
                getter: getGet
                setter: setGet
            xml_list:
                inline: true
                entry_name: get
            type: array<macropage\sdks\plesk\types\ResellerGetInputType>
        del:
            expose: true
            access_type: public_method
            serialized_name: del
            accessor:
                getter: getDel
                setter: setDel
            xml_list:
                inline: true
                entry_name: del
            type: array<macropage\sdks\plesk\types\ResellerDelInputType>
        ippoolAddIp:
            expose: true
            access_type: public_method
            serialized_name: ippool-add-ip
            accessor:
                getter: getIppoolAddIp
                setter: setIppoolAddIp
            xml_list:
                inline: true
                entry_name: ippool-add-ip
            type: array<macropage\sdks\plesk\types\ResellerIpPoolOperationType>
        ippoolDelIp:
            expose: true
            access_type: public_method
            serialized_name: ippool-del-ip
            accessor:
                getter: getIppoolDelIp
                setter: setIppoolDelIp
            xml_list:
                inline: true
                entry_name: ippool-del-ip
            type: array<macropage\sdks\plesk\types\ResellerIpPoolDelInputType>
        ippoolSetIp:
            expose: true
            access_type: public_method
            serialized_name: ippool-set-ip
            accessor:
                getter: getIppoolSetIp
                setter: setIppoolSetIp
            xml_list:
                inline: true
                entry_name: ippool-set-ip
            type: array<macropage\sdks\plesk\types\IpPoolResellerSetType>
        cformButtonsList:
            expose: true
            access_type: public_method
            serialized_name: cform-buttons-list
            accessor:
                getter: getCformButtonsList
                setter: setCformButtonsList
            xml_list:
                inline: true
                entry_name: cform-buttons-list
            type: array<macropage\sdks\plesk\types\ResellerInputType\CformButtonsListAnonymousType>
        getLimitDescriptor:
            expose: true
            access_type: public_method
            serialized_name: get-limit-descriptor
            accessor:
                getter: getGetLimitDescriptor
                setter: setGetLimitDescriptor
            xml_list:
                inline: true
                entry_name: get-limit-descriptor
            type: array<macropage\sdks\plesk\types\ResellerInputType\GetLimitDescriptorAnonymousType>
        getPermissionDescriptor:
            expose: true
            access_type: public_method
            serialized_name: get-permission-descriptor
            accessor:
                getter: getGetPermissionDescriptor
                setter: setGetPermissionDescriptor
            xml_list:
                inline: true
                entry_name: get-permission-descriptor
            type: array<macropage\sdks\plesk\types\ResellerInputType\GetPermissionDescriptorAnonymousType>
        convertToCustomer:
            expose: true
            access_type: public_method
            serialized_name: convert-to-customer
            accessor:
                getter: getConvertToCustomer
                setter: setConvertToCustomer
            xml_list:
                inline: true
                entry_name: convert-to-customer
            type: array<macropage\sdks\plesk\types\ResellerInputType\ConvertToCustomerAnonymousType>
        switchSubscription:
            expose: true
            access_type: public_method
            serialized_name: switch-subscription
            accessor:
                getter: getSwitchSubscription
                setter: setSwitchSubscription
            xml_list:
                inline: true
                entry_name: switch-subscription
            type: array<macropage\sdks\plesk\types\ResellerInputType\SwitchSubscriptionAnonymousType>
        syncSubscription:
            expose: true
            access_type: public_method
            serialized_name: sync-subscription
            accessor:
                getter: getSyncSubscription
                setter: setSyncSubscription
            xml_list:
                inline: true
                entry_name: sync-subscription
            type: array<macropage\sdks\plesk\types\ResellerInputType\SyncSubscriptionAnonymousType>
        addPackage:
            expose: true
            access_type: public_method
            serialized_name: add-package
            accessor:
                getter: getAddPackage
                setter: setAddPackage
            xml_list:
                inline: true
                entry_name: add-package
            type: array<macropage\sdks\plesk\types\ResellerApplicationInputType>
        removePackage:
            expose: true
            access_type: public_method
            serialized_name: remove-package
            accessor:
                getter: getRemovePackage
                setter: setRemovePackage
            xml_list:
                inline: true
                entry_name: remove-package
            type: array<macropage\sdks\plesk\types\ResellerApplicationInputType>
        enableApsFilter:
            expose: true
            access_type: public_method
            serialized_name: enable-aps-filter
            accessor:
                getter: getEnableApsFilter
                setter: setEnableApsFilter
            xml_list:
                inline: true
                entry_name: enable-aps-filter
            type: array<macropage\sdks\plesk\types\ResellerApsFilterTypeInputType>
        disableApsFilter:
            expose: true
            access_type: public_method
            serialized_name: disable-aps-filter
            accessor:
                getter: getDisableApsFilter
                setter: setDisableApsFilter
            xml_list:
                inline: true
                entry_name: disable-aps-filter
            type: array<macropage\sdks\plesk\types\ResellerApsFilterTypeInputType>

````
